version: '3'

services:
  employees-postgres:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: password

  employees-app:
    image: employees
    restart: always
    depends_on:
      - employees-postgres
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://employees-postgres/postgres'
    entrypoint: ["./wait-for-it.sh", "-t", "120", "employees-postgres:5432", "--", "java", "-jar", "employees.jar"]
    expose:
      - 8080
    scale: 2

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - locations-app
    ports:
      - "8089:8081"